import {combineReducers} from 'redux';
import DefaultReducers from './DefaultReducers';
import loadingReducers from './LoadingReducer';

const reducers = combineReducers({
  register: DefaultReducers,
  verifyData: DefaultReducers,
  resendOtpData: DefaultReducers,
  setPasswordData: DefaultReducers,
  loginData: DefaultReducers,
  forgotEmail: DefaultReducers,
  profileData: DefaultReducers,
  logoutData: DefaultReducers,
  forgotOtpData: DefaultReducers,
  getRegionList: DefaultReducers,
  getCategory: DefaultReducers,
  getMedicalExpertiesList: DefaultReducers,
  getLanguageList: DefaultReducers,
  getAllFieldsList: DefaultReducers,
  bookingModeShiftList: DefaultReducers,
  bookingModeShiftRequestList: DefaultReducers,
  postJobList: DefaultReducers,
  getLatLongDataApi: DefaultReducers,
  getHomeApiData: DefaultReducers,
  getJobPostData: DefaultReducers,
  socialLoginData: DefaultReducers,
  jobAppliedList: DefaultReducers,
  jobPostedAppliedDetail: DefaultReducers,
  postjobtitlelist: DefaultReducers,
  sendJobOffer: DefaultReducers,
  postjobShiftValidation: DefaultReducers,
  createpaymentIntents: DefaultReducers,
  createBookingRequestpayment: DefaultReducers,
  declineSericeAgrementList: DefaultReducers,
  getCarerSearchList: DefaultReducers,
  getCarerListDetails: DefaultReducers,
  getAvailabiltiesDate: DefaultReducers,
  filterDropDownList: DefaultReducers,
  getCategorybasedTraining: DefaultReducers,
  bookAnAppointmentData: DefaultReducers,
  confirmBookingData: DefaultReducers,
  carerBookReqData: DefaultReducers,
  getJobPostDetailsData: DefaultReducers,
  myBookingsDeaital: DefaultReducers,
  getPopularSearchData: DefaultReducers,
  offerDeclineReasonData: DefaultReducers,
  getPostJobDropDownLists: DefaultReducers,
  getViewProposalLists: DefaultReducers,
  getViewServiceAgreementLists: DefaultReducers,
  getlatLog: DefaultReducers,
  bookAppointment: DefaultReducers,
  updateConfirmBooking: DefaultReducers,
  paymentDetails: DefaultReducers,
  declineJobOffer: DefaultReducers,
  paymentDetailData: DefaultReducers,
  declineReasonCarerData: DefaultReducers,
  acceptAgreementValidationData: DefaultReducers,
  serviceRequestData: DefaultReducers,
  cancelRequestServiceData: DefaultReducers,
  applyPromoCodeData: DefaultReducers,
  couponListData: DefaultReducers,
  cancelCareSeekerBookingData: DefaultReducers,
  paymentSummaryData: DefaultReducers,
  submitReviewData: DefaultReducers,
  reviewListingData: DefaultReducers,
  invoiceApprovalList: DefaultReducers,
  declineInvoiceData: DefaultReducers,
  AcceptInvoiceData: DefaultReducers,
  paymentApproveInvoiceData: DefaultReducers,
  getCancelBookingInfodata: DefaultReducers,
  carerReviewListingdata: DefaultReducers,
  getCreateSupportData: DefaultReducers,
  CreateSupportData: DefaultReducers,
  getUpdateProfileData: DefaultReducers,
  updateProfileData: DefaultReducers,
  getNationalities: DefaultReducers,
  paymentData: DefaultReducers,
  notificationData: DefaultReducers,
  isLoading: loadingReducers,
  read_notification: DefaultReducers,
  delete_accounts: DefaultReducers,
  chat_block_report_user: DefaultReducers,
  report_user: DefaultReducers,
  getCategorybasedProfessioanlExperieneces: DefaultReducers,
});

export default reducers;
